# Generated by Django 2.2.2 on 2019-09-02 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="ft.Subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="feeds.Source",
            ),
        ),
    ]
