# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0002_auto_20170531_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='needs_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
