# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 06:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0003_source_needs_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
