# Generated by Django 4.2.3 on 2024-02-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_source_last_read_subscription'),
        ('ft', '0005_alter_subscription_parent_alter_subscription_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpost',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.subscription'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
