# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0005_auto_20170628_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='maxIndex',
            new_name='max_index',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='isRiver',
            new_name='is_river',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='lastRead',
            new_name='last_read',
        ),
    ]
