# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 17:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0007_auto_20170628_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpost',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ft.Subscription'),
        ),
    ]
