# Generated by Django 2.2.1 on 2019-06-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0008_savedpost_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebProxy',
        ),
        migrations.AlterField(
            model_name='source',
            name='last302url',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salutation',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='What should we call you?'),
        ),
    ]
