# Generated by Django 2.2.1 on 2019-06-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0009_auto_20190602_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='last302start',
            new_name='last_302_start',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='last302url',
            new_name='last_302_url',
        ),
    ]
