# Generated by Django 2.2.1 on 2019-06-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0010_auto_20190603_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='needs_proxy',
            new_name='is_cloudflare',
        ),
    ]
