# Generated by Django 2.2.1 on 2019-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0011_auto_20190603_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['index']},
        ),
    ]
