# Generated by Django 2.2.1 on 2019-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0012_auto_20190603_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='due_poll',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_302_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
