# Generated by Django 2.2.1 on 2019-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0014_enclosure'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enclosure',
            table='feeds_enclosure',
        ),
    ]
