# Generated by Django 2.2.1 on 2019-06-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0015_auto_20190603_1645'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='feeds_post',
        ),
    ]
