# Generated by Django 2.2.1 on 2019-06-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0016_auto_20190603_1646'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='source',
            table='feeds_source',
        ),
    ]
